@extends('layouts.app')

@section('content')
    @include('web.partials._hero')
    @include('web.partials._about')
    @include('web.partials._causes')
    @include('web.partials._volunters')
    @include('web.partials._event')
    @include('web.partials._features')
    @include('web.partials._brand')
    @include('web.partials._testi')
    @include('web.partials._gallery')
    @include('web.partials._faq')
    @include('web.partials._counter')
    @include('web.partials._news')
@endsection
